language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'sailor-base' ]; then cd .. && eval "mv $currentfolder sailor-base" && cd sailor-base; fi
