language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'sailor-scripts' ]; then cd .. && eval "mv $currentfolder sailor-scripts" && cd sailor-scripts; fi
